name: Auto Commit Updated Status

on:
  push:
    paths:
      - 'data/status.json'

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit updated status.json
        run: |
          git add data/status.json
          git commit -m "🟢 Update service status" || echo "No changes to commit"
          git push
